### ISSUE TITLE
Project Feedback

### ISSUE THREAD

**Issue by levinsonmm** [levinsonmm/MI-449-SS17-741-js-conditionals-uMDt4P#1]
@KatieMFritz Can you take a look at this? It's [hosted here](https://levinsonmm.github.io/MI-449-SS17-741-js-conditionals-uMDt4P/) and meets the following criteria:

- [x] Use the `prompt` and `confirm` functions (each at least once) to collect choices from the user (the entire story will take place in dialog boxes, so your `body` element could actually be empty, apart from the `script` element to include your JavaScript)
- [x] Use `if`, `else if`, and `else` to branch the story, based on user choices
- [x] In at least one branch, there should be at least 3 choices for the user to make
- [x] Include at least one branch where different things can happen each time with `Math.random()`
- [x] Use a logical operator (`&&` or `||`) at least once, where it makes sense
- [x] It should be impossible for an error to ever occur when playing your game, including handling for `null`/`undefined` where appropriate
- [x] All string input should be normalized, so that extra whitespace or a letter that's the wrong case will never cause a failed match
- [x] At least one number value is collected and used in a comparison (don't forget to convert it into a number first)
- [x] Don't get _too_ carried away -- it can be tempting to build a complex video game, but remember, you can always come back and build on this project later

**Comment by KatieMFritz** [comment]
lololololol I laughed so hard I disturbed the section before yours. 😆 Great replay value too. I adopted a demon rat and named it demonRat (I'm into descriptive variable names), turned down adopting 100 squirrels, adopted a TINY BABY CAT SO CUTE, adopted a demon cat named Cookie, adopted a perfect cat named MacGyver (this is a true story and I CAN send you pics), and wasted your time on a dog. Sorry, dog. 

I'm really impressed by the way you used the `pet` variable and lots of branch options to make the responses more customized. It felt fresh every time. 🐶 🐱 🐀 You also have some sophisticated JS in there! The `for` loop and `%` operator go above and beyond. 😮 You did a nice job separating your logic into functions as well. 👍 

### Age edge cases
I tried, but I couldn't break the game! The only thing that didn't quite make sense is I could enter ages like -1 and 5000 without the game realizing that was weird, and if I enter 18, I get "18 is over 18." 

### Typos
There's a small typo at [line 60](https://github.com/levinsonmm/MI-449-SS17-741-js-conditionals-uMDt4P/blob/master/script.js#L60) - no space between `other` and `pet`, so it gets mashed together. 

### Variable names
In general, your variable names are 🔥! The `clause` variable is a little confusing to me. What would you think about renaming it to `attribute` or `adjective` or `situation`? 

* * *
After you’ve made your changes and pushed them to GitHub and your hosted site, give it a once-over to make sure it looks right, then comment back here and I’ll take another look.

Thanks! :rocket:

PS Would it be okay to share your project with a couple friends? It made me laugh so hard. Especially the branch where you have to adopt 100 pets. 😂

**Comment by levinsonmm** [comment]
I added a few more cases for age, fixed that typo on like 60, and changed 'clause' to 'situation'. 

You're more than welcome to share this project with your friends!

Thanks for the awesome feedback! 😺

**Comment by KatieMFritz** [comment]
Great job with those new cases for `age` - and with the comments explaining why. You also did an excellent job committing each feature as you completed it, with descriptive commit messages. 🔥 

:shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: 
:shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: 
:shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: 
:shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: 
:shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: 
:shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: 
:shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: 
:shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: 
:shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: 
:shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit:

**Comment by levinsonmm** [comment]
Thanks!
